---
# Author metadata
author: [Shane Martin]
email: [email address]
affiliation: |
  | [course code]
  | [course name]
address: |
  | [supervisor]
  | [department]
  | [school]

# Report metadata
report_name: 'report'
classoption: draftfirst
copyright: Copyright (c) 2014 by Shane Martin.  All Rights Reserved.
title: [paper title]
shorttitle:
abstract: |
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
keywords: [Lorem ipsum, dolor, sit amet, consectetur adipisicing]

# References
refs: etc/biblio.bib

# Citation styles
csl_url: https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl
csl: etc/apa.csl
---
